apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  generation: 1
  labels:
    app: cpueater
    jon: jon
  name: cpueater
  namespace: load-test
spec:
  replicas: 50
  revisionHistoryLimit: 10
  selector:
    app: cpueater
    deploymentconfig: cpueater
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cpueater
        deploymentconfig: cpueater
    spec:
      containers:
        - image: >-
            docker-registry.default.svc:5000/load-test/cpueater
          imagePullPolicy: Always
          name: cpueater
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "100Mi"
      nodeSelector:
        loadtest: "yes"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - cpueater
        from:
          kind: ImageStreamTag
          name: 'cpueater:latest'
          namespace: load-test
      type: ImageChange
